services:
  postgres_db:
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - ./migrations/auth_go.sql:/docker-entrypoint-initdb.d/auth_go.sql
      - ./database/auth_go:/var/lib/postgresql/data
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped

  rest_server:
    restart: unless-stopped
    container_name: rest
    build:
      context: .
      dockerfile: Dockerfile
    command: go run /app/cmd/main.go
    ports:
      - "3000:3000"
